### ISSUE TITLE
Addon not working

### ISSUE THREAD

**Issue by jay78887** [sleeyax/stremio-consumet-addon#2]
New to this addon but I installed it and it doesn't seem to work.
Says it pulls from dramacool - when searching up a series that's uploaded on dramacool, it doesn't show.
There is no tab down for sources for consumet like it has for torrentio.

**Comment by sleeyax** [comment]
The [Consumet API](https://api.consumet.org/) is down so the addon can't pull in new sources. That's probably why.

**Comment by sleeyax** [comment]
Fixed in https://github.com/sleeyax/stremio-consumet-addon/pull/37
